[DEFAULT]
gelbooru_id = 
gelbooru_key = 
rule34_id = 
rule34_key = 
safebooru_id = 
safebooru_key = 
danbooru_id = 
danbooru_key = 
konachan_id = 
konachan_key = 
yande.re_id = 
yande.re_key = 
aibooru_id = 
aibooru_key = 
xbooru_id = 
xbooru_key = 
e621_id = 
e621_key = 

[UserKeys]

